config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  end
  get "home/index"
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "home#index"
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_admin_user

  def index
    @users = User.all.order(:id)
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      respond_to do |format|
        format.html { redirect_to admin_users_path, notice: "ユーザーが作成されました。" }
        format.turbo_stream
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      respond_to do |format|
        format.html { redirect_to admin_user_path(@user), notice: "ユーザーが更新されました。" }
        format.turbo_stream
      end
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    respond_to do |format|
      format.html { redirect_to admin_users_path, notice: "ユーザーが削除されました。" }
      format.turbo_stream
    end
  end

  private

  def ensure_admin_user
    unless current_user.admin?
      redirect_to root_path, alert: "管理者権限が必要です。"
    end
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :admin)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  def after_sign_in_path_for(resource)
    if resource.admin?
      admin_users_path # スーパーユーザーはユーザー管理画面に遷移
    else
      root_path # 通常のユーザーはホーム画面に遷移
    end
  end

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/admin/users/_user.html.slim
tr id=dom_id(user)
  td.px-4.py-2.border.border-gray-300 = user.id
  td.px-4.py-2.border.border-gray-300 = user.name
  td.px-4.py-2.border.border-gray-300 = user.email
  td.px-4.py-2.border.border-gray-300 = user.created_at.strftime("%Y-%m-%d")
  td.flex.px-4.py-2.border.border-gray-300.justify-center
    = link_to '編集', edit_admin_user_path(user), data: { turbo_frame: "user_form" }, class: 'bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-600 transition duration-200 mr-2'
    = link_to '削除', admin_user_path(user), method: :delete, data: { confirm: "本当に削除しますか？" }, class: 'bg-red-500 text-white px-4 py-2 rounded hover:bg-red-600 transition duration-200'

app/views/admin/users/create.turbo_stream.erb
<%= turbo_stream.remove "user_form" %>
<%= turbo_stream.append "users", partial: "admin/users/user", locals: { user: @user } %>

app/views/admin/users/destroy.turbo_stream.erb
<%= turbo_stream.remove dom_id(@user) %>

app/views/admin/users/edit.html.slim
turbo-frame#user_form
  div.bg-gray-100.shadow-lg.rounded-lg.p-8.max-w-2xl.mx-auto
    h2.text-2xl.font-semibold.text-gray-800.mb-6 ユーザー編集

    = form_with model: @user, url: admin_user_path(@user), method: :patch, class: "space-y-6" do |f|
      .flex.flex-wrap.gap-4
        .m-x-2.w-full
          = f.label :name, "名前", class: "block text-sm font-medium text-gray-700 mb-2"
          = f.text_field :name, class: "block w-full border border-gray-300 rounded-lg shadow-sm px-4 py-2 focus:ring-blue-500 focus:border-blue-500"
        .m-x-2.w-full
          = f.label :email, "メールアドレス", class: "block text-sm font-medium text-gray-700 mb-2"
          = f.email_field :email, class: "block w-full border border-gray-300 rounded-lg shadow-sm px-4 py-2 focus:ring-blue-500 focus:border-blue-500"
        .m-x-2.w-full
          = f.label :password, "パスワード", class: "block text-sm font-medium text-gray-700 mb-2"
          = f.password_field :password, class: "block w-full border border-gray-300 rounded-lg shadow-sm px-4 py-2 focus:ring-blue-500 focus:border-blue-500"
        .m-x-2.w-full
          = f.label :password_confirmation, "パスワード確認", class: "block text-sm font-medium text-gray-700 mb-2"
          = f.password_field :password_confirmation, class: "block w-full border border-gray-300 rounded-lg shadow-sm px-4 py-2 focus:ring-blue-500 focus:border-blue-500"
        .m-x-2.w-full.flex.justify-end.gap-4
          = f.submit '作成', class: "w-32 bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-600 transition duration-200"
          = link_to 'キャンセル', admin_users_path, class: "w-32 bg-red-500 text-white px-4 py-2 rounded hover:bg-red-600 transition duration-200"

app/views/admin/users/index.html.slim
div.container.mx-auto.px-4
  h1.text-3xl.font-bold.text-center.mb-6 ユーザー一覧

  div.flex.justify-end.mb-4
    = link_to '新規作成', new_admin_user_path, data: { turbo_frame: "user_form" }, class: 'bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-600'

  div.flex.justify-center
    table.table-auto.border-collapse.border.border-gray-300.w-full
      thead
        tr.bg-gray-200
          th.px-4.py-2.border.border-gray-300 ID
          th.px-4.py-2.border.border-gray-300 名前
          th.px-4.py-2.border.border-gray-300 メールアドレス
          th.px-4.py-2.border.border-gray-300 作成日
          th.px-4.py-2.border.border-gray-300 操作
      tbody#users
        - @users.each do |user|
          = render partial: "admin/users/user", locals: { user: user }

  turbo-frame#user_form

app/views/admin/users/new.html.slim
turbo-frame#user_form
  div.bg-gray-100.shadow-lg.rounded-lg.p-8.max-w-2xl.mx-auto
    h2.text-2xl.font-semibold.text-gray-800.mb-6 ユーザー作成

    - if @user.errors.any?
      div.bg-red-100.text-red-700.p-4.rounded.mb-4
        ul
          - @user.errors.full_messages.each do |message|
            li = message

    = form_with model: @user, url: admin_users_path, method: :post, class: "space-y-6" do |f|
      .flex.flex-wrap.gap-4
        .m-x-2.w-full
          = f.label :name, "名前", class: "block text-sm font-medium text-gray-700 mb-2"
          = f.text_field :name, class: "block w-full border border-gray-300 rounded-lg shadow-sm px-4 py-2 focus:ring-blue-500 focus:border-blue-500"
        .m-x-2.w-full
          = f.label :email, "メールアドレス", class: "block text-sm font-medium text-gray-700 mb-2"
          = f.email_field :email, class: "block w-full border border-gray-300 rounded-lg shadow-sm px-4 py-2 focus:ring-blue-500 focus:border-blue-500"
        .m-x-2.w-full
          = f.label :password, "パスワード", class: "block text-sm font-medium text-gray-700 mb-2"
          = f.password_field :password, class: "block w-full border border-gray-300 rounded-lg shadow-sm px-4 py-2 focus:ring-blue-500 focus:border-blue-500"
        .m-x-2.w-full
          = f.label :password_confirmation, "パスワード確認", class: "block text-sm font-medium text-gray-700 mb-2"
          = f.password_field :password_confirmation, class: "block w-full border border-gray-300 rounded-lg shadow-sm px-4 py-2 focus:ring-blue-500 focus:border-blue-500"
        .m-x-2.w-full.flex.justify-end.gap-4
          = f.submit '作成', class: "w-32 bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-600 transition duration-200"
          = link_to 'キャンセル', admin_users_path, class: "w-32 bg-red-500 text-white px-4 py-2 rounded hover:bg-red-600 transition duration-200"

app/views/admin/users/update.turbo_stream.erb
<%= turbo_stream.remove "user_form" %>
<%= turbo_stream.replace dom_id(@user), partial: "admin/users/user", locals: { user: @user } %>

app/views/home/index.html.slim
div.container.mx-auto.mt-10.px-4
  div.flex.justify-between.items-center.mb-6
    h1.text-3xl.font-bold.text-black-500 ホーム画面
    = link_to 'ログアウト', destroy_user_session_path, method: :delete, data: { turbo: false }, class: 'bg-red-500 text-white py-2 px-5 rounded-lg hover:bg-red-600 transition duration-200'
    / = link_to 'ログアウト', destroy_user_session_path, method: :delete, data: { turbo: false }, class: 'btn btn-danger'

  p.text-gray-700.mb-4
    | このページはホーム画面です。ログイン状態を維持しています。

  div.grid.grid-cols-1.md:grid-cols-2.lg:grid-cols-3.gap-4
    div.bg-white.shadow-md.rounded-lg.p-4
      h2.text-xl.font-semibold.text-gray-800 Card 1
      p.text-gray-600 ここにカードの内容を記述します。
    div.bg-white.shadow-md.rounded-lg.p-4
      h2.text-xl.font-semibold.text-gray-800 Card 2
      p.text-gray-600 ここにカードの内容を記述します。
    div.bg-white.shadow-md.rounded-lg.p-4
      h2.text-xl.font-semibold.text-gray-800 Card 3
      p.text-gray-600 ここにカードの内容を記述します。

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Todo Create" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header class="bg-gray-800 text-white p-6 flex justify-end items-center">
      <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, data: { turbo: false }, class: 'bg-red-500 text-white py-2 px-5 rounded-lg hover:bg-red-600 transition duration-200' %>
    </header>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>